### ISSUE TITLE
Add New login pages

### ISSUE THREAD

**Issue by abhir9** [LoginRadius/awesome-login-pages#1]

**Comment by AyoubBoulahtar** [comment]
I can work on these. Can you assign me ?

**Comment by abhir9** [comment]
@AyoubBoulahtar assigned ,

still if anyone raise PR early related to this issue can be reassigned.
or if you are not able to work on it let me know i can reassign.

**Comment by AyoubBoulahtar** [comment]
Okay, thank you.

**Comment by AyoubBoulahtar** [comment]
Hello, should all the login pages be in html css javascript, or can I use other technologies as well like flutter ?

**Comment by ManasDroid** [comment]
can you assign me this issue ?

**Comment by Swatigupta-droid** [comment]
Can you assign this issue to me ?

**Comment by AyoubBoulahtar** [comment]
@ManasDroid  @Swatigupta-droid you can make a PR without being an assignee just respect the contribution guide and open you pr.

**Comment by abhir9** [comment]
@AyoubBoulahtar  we are keeping this to html, js, css , not something which require additional setup

**Comment by satyam73** [comment]
Can I make and add login page without getting assigned?

**Comment by abhir9** [comment]
@satyam73  yes you can raise PR

**Comment by vishwa511** [comment]
Can i add a new login page

**Comment by ankur2825** [comment]
hello sir can you assign me this issue?

**Comment by soumyajit4419** [comment]
Can i add a new login page

**Comment by satyam73** [comment]
Hello @abhir9 I have created a PR #35 .
Please check it.

**Comment by tamojeetK** [comment]
Can somebody tell me how should I name the folder which I'm gonna add?

**Comment by Palaksharma23** [comment]
hello @abhir9 can you please assign me this issue

**Comment by tamojeetK** [comment]
@abhir9 I have recently added PR #36 pls check it and let me know if any further changes are needed to be done.
 There may be Conflicts. Pls check it.

✅Saved my changes by following the instructions.
✅Uploaded the screenshot of my page.
✅Added profile details in Awesome Login pages README.md file (Name | Desktop Screenshot | Contributed by).

**Comment by MananDudhwala** [comment]
Can I have a go at this issue?

**Comment by soumyajit4419** [comment]
@abhir9 I have recently added PR #45 pls check it and let me know if any changes are needed. 
There may be some merge conflict please do tell me if any changes are required.

**Comment by kartikeytandon** [comment]
Hey, please assign this task to me.

**Comment by CoderNehal** [comment]
kindly assign me this @abhir9

**Comment by AmreshSinha** [comment]
@abhir9 I have opened a PR #66 . Kindly Check it out 🚀 . Built on Neumorphic UI. If there any problem I will try fix it 👍 .

**Comment by PrerakMathur20** [comment]
Hello,
I have submitted my PR #71 with a new login page. Kindly Review and merge it at your earliest convenience.

**Comment by DelayCoderz** [comment]
@abhir9 i have sumbitted my PR #77. pls review it and give feedback :)

**Comment by AmreshSinha** [comment]
@abhir9 there should be a better structure for naming so that everyone has unique folder names different from other.

**Comment by harshitacodes** [comment]
@abhir9 Submitted my PR #73 Please review!

**Comment by nitheesh96** [comment]
i would love to work on this issue
