### ISSUE TITLE
Not able to add a new screenshot in login-form-v15

### ISSUE THREAD

**Issue by Yashism** [LoginRadius/awesome-login-pages#25]
I created a repo named login-form-v15 and I added index.html and I was going to upload style.css but someone added it before me and now I'm not able to upload any file in it

**Comment by abhir9** [comment]
@Yashism  No worries, This is continous process all contributors will continue adding the changes. now you can rename the folder login-form-v17,   make sure you take latest changes before raising/updating PR and do changes on top of that so there will be no conflict
