### ISSUE TITLE
Add contributors section in readme.md 

### ISSUE THREAD

**Issue by Abhijay007** [LoginRadius/awesome-login-pages#41]
Add contributors section in the readme.MD something like this !!

![snip](https://user-images.githubusercontent.com/64387054/135712498-1a764bce-04c4-441a-a5d5-c0cea03b4827.PNG)

**Comment by Abhijay007** [comment]
@abhir9  can I work on this issue?

**Comment by MananDudhwala** [comment]
Can I work on this issue?I'll try to deliver as  soon as possible!

**Comment by Abhijay007** [comment]
Hi, @MananDudhwala I am already working on it 😅.

**Comment by MananDudhwala** [comment]
Oh! Sure!

**Comment by Abhijay007** [comment]
closed via #41
